import { Fragment, useEffect, useRef } from 'react'
import { evidence } from '../data/evidence'
import { historySources, historyAdditionalSources } from '../data/historySources'
import { chapters } from '../data/copy'
import { useWorld } from './WorldState'
import { goToScene, goToHistory, acquireScrollLease } from './WorldTimeline'
import { useGuideApi } from '../onboarding/guideControls'
export function SourceDrawer({mode,index,onClose,onSource}:{mode:'menu'|'source'|'history';index:number;onClose:()=>void;onSource:(index:number)=>void}) {
  const guide=useGuideApi(),dialog=useRef<HTMLDialogElement>(null),state=useWorld(), items=mode==='history'?historySources:evidence, item=items[index]
  useEffect(()=>{const el=dialog.current,previous=document.activeElement as HTMLElement|null;el?.showModal();document.body.classList.add('drawer-open');const release=acquireScrollLease('dialog');return()=>{el?.close();release();document.body.classList.remove('drawer-open');previous?.focus({preventScroll:true})}},[])
  return <dialog ref={dialog} className="source-drawer" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}} data-lenis-prevent>
    <div className="drawer-inner"><div className="drawer-top"><span className="eyebrow">{mode==='menu'?'MẠCH / MỤC LỤC':'TƯ LIỆU / '+item.code}</span><button onClick={onClose} aria-label="Đóng bảng">×</button></div>
    {mode==='menu'?<><nav className="chapter-menu" aria-label="Mục lục">{chapters.map((name,i)=><Fragment key={name}><button onClick={()=>{state.set({unlocked:true});onClose();requestAnimationFrame(()=>goToScene(i))}}><span>{String(i).padStart(2,'0')}</span>{name}<span>↗</span></button>{i===1&&<button onClick={()=>{onClose();goToHistory()}}><span>01.H</span>Bản đồ lịch sử<span>↗</span></button>}</Fragment>)}</nav><div className="menu-settings" data-guide="menu-settings"><button onClick={()=>state.set({sound:!state.sound})}>Âm thanh <span>{state.sound?'BẬT':'TẮT'}</span></button><button onClick={()=>state.set({paused:!state.paused})}>Chuyển động <span>{state.paused?'TẠM DỪNG':'ĐANG CHẠY'}</span></button><button onClick={()=>onSource(0)}>Tư liệu & cơ sở lý luận <span>↗</span></button><button onClick={()=>{onClose();requestAnimationFrame(()=>guide?.openReplayMenu())}}>Cú Mạch / Hướng dẫn &amp; xem lại <span>↗</span></button></div><p className="drawer-note">Những không gian phát triển giúp quan sát sự biến đổi của LLSX và yêu cầu thích ứng của QHSX; không phải năm phương thức sản xuất.</p></>:<><h2>{item.topic}</h2><p className="source-summary">{item.text}</p><dl data-guide="history-source case-source finale-source"><dt>TƯ LIỆU</dt><dd>{item.source}</dd><dt>MỐC THỜI GIAN</dt><dd>{item.year}</dd><dt>CƠ QUAN / NGUỒN</dt><dd>{item.agency}</dd><dt>VỊ TRÍ ĐỐI CHIẾU</dt><dd>{item.location}</dd></dl><a className="original-source" href={item.url} target="_blank" rel="noreferrer">ĐỌC NGUỒN GỐC <span>↗</span></a><div className="theory-note"><span className="eyebrow">LIÊN HỆ LÝ LUẬN · DIỄN GIẢI</span><p>{item.mapping}</p></div><details><summary>Cơ sở lý luận của trải nghiệm</summary><p>Lực lượng sản xuất phản ánh năng lực thực tiễn của xã hội trong quá trình sản xuất, gồm người lao động và tư liệu sản xuất.</p><p>QHSX có ba mặt: sở hữu đối với tư liệu sản xuất; tổ chức và quản lý sản xuất; phân phối sản phẩm lao động.</p><p>Mô phỏng minh họa quan hệ phù hợp và mâu thuẫn. Các mức điều chỉnh không phải số liệu kinh tế hay đánh giá chính sách.</p></details><div className="drawer-source-nav">{items.map((e,i)=><button key={e.code} aria-current={index===i?'true':undefined} onClick={()=>onSource(i)}>{e.code}</button>)}</div></>}
    {mode==='history'&&<details><summary>Tư liệu đối chiếu bổ sung</summary>{historyAdditionalSources.map(source=><p key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.source} ↗</a></p>)}</details>}<a className="asset-credits" href="/ASSET-CREDITS.md" target="_blank" rel="noreferrer">Nguồn mô hình & vật liệu ↗</a></div>
  </dialog>
}
